"""Single-leg tip workspace of Urdf_Bennett_3 -- reproduction of Fig. 5 in
"Overconstrained coaxial design of robotic legs with omni-directional
locomotion" (Gu et al., Mechanism and Machine Theory 176, 2022).

Mechanism structure (verified numerically, see outputs/_mobility_check.py):
  * The closed loop base->thigh(q1)->calf(q2)->_3->(spherical)->_2->(_1)->thigh
    has mobility 1 once the thigh frame is fixed: for a GIVEN q2 the passive
    angles (q3,q4,q5) and the tip position in the thigh frame are uniquely
    determined -- independent of q1 (q5 = q2 holds exactly).
  * q1 therefore only rotates the whole leg about the coaxial drive axis
    U1 = (0, 1, 1)/sqrt(2): the workspace is the SURFACE OF REVOLUTION of the
    1-D generator curve g(q2) about the drive axis -- exactly the generation
    principle stated in the paper ("generated by rotating a line in 3D space",
    their generator is near-semicircular -> half-cut-away torus).
  * The physical branch is 4*pi periodic in the configuration but the TIP locus
    closes after one period to within 3 mm (period-3 arc = period-1 arc exactly),
    so one period of g closes into a ring for plotting.

Display orientation: the FR leg is plotted (exact mirror of FL in y, verified
against bennett_1.xml: FR_thigh axis (0,-1,1)/sqrt2, identical joint ranges), so
the drive axis U = (0,-1,1)/sqrt2 runs UPPER-LEFT to LOWER-RIGHT in the y-z side
view -- the same orientation as the paper's z1 (Fig. 4) and its side-view band.

Sweeps
  generator : q2 over one full period (continuation from the straight assembly
              at q2 = 0, with random-restart rescue through the steep region)
  surface   : q1 over a full cycle applied analytically (exact, not re-solved)
  fig5_workspace          : three-view figure; isometric is a half-cut-away
                            (lower half of the revolution kept, cut edges show
                            the generator curve), side/front views show the
                            full projection like the paper
  fig5_workspace_full     : same figure with the full-torus isometric
  fig5b_workspace_limited : hardware-limited usable patch (thigh +/-0.8 rad,
                            calf -0.9..+0.55 rad) and the rest-pose tip

All coordinates are hip frame (origin = thigh joint centre, robot body axes),
in millimetres. Geometry is taken from sim2sim/models/bennett_1/bennett_1.xml.

Usage:
  python scripts/analysis/plot_bennett_workspace.py                 # cached scan + plot
  python scripts/analysis/plot_bennett_workspace.py --rescan        # re-scan generator
  python scripts/analysis/plot_bennett_workspace.py --n_gen 1441    # denser generator
"""

import argparse
import sys
import time
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from bennett_leg_fk import rot_axis, solve_passive, U1  # noqa: E402

OUT_DIR = Path(r"e:/Project/Isaaclab/bennett_rl/source/bennett_rl/bennett_rl/assets/kinematics")
SURFACE = "#fcfcfb"
INK = "#0b0b0b"
INK2 = "#52514e"
MUTED = "#898781"
GRID = "#e1e0d9"

# display orientation: mirror y -> FR leg; drive axis becomes (0,-1,1)/sqrt2,
# i.e. the upper-left -> lower-right diagonal of the y-z plane
MIR = np.array([1.0, -1.0, 1.0])
U_PLOT = U1 * MIR

THIGH_LIMIT = 0.8        # rad, from bennett_1.xml joint ranges
CALF_LIMITS = (-0.9, 0.55)
Q2_START = 0.0           # straight assembly, passive = (0, 0, 0)


# ------------------------------------------------------------------ scanning --
def solve_tracked(q2, x_warm, x_pred, rng, tip_pred=None):
    """Closure solve that stays on the physical sheet through the steep
    multi-root zone: continuation first, then restarts at growing sigma,
    always keeping the root closest to the linear prediction x_pred."""
    cands = []
    x, e, foot = solve_passive(0.0, q2, x_warm)
    if e < 1e-10:
        cands.append((np.linalg.norm(x - x_pred), x, foot))
    for sig in (0.3, 0.8, 1.5, 2.5):
        for _ in range(10):
            x0 = x_warm + rng.normal(0.0, sig, 3)
            x2, e2, f2 = solve_passive(0.0, q2, x0)
            if e2 < 1e-10:
                d = np.linalg.norm(x2 - x_pred)
                cands.append((d, x2, f2))
    if not cands:
        return None, None
    cands.sort(key=lambda c: c[0])
    return cands[0][1], cands[0][2]


def scan_generator(n=721):
    """One full period of the generator curve g(q2), hip frame, mm."""
    q2s = Q2_START + np.arange(n) * (2.0 * np.pi / n)
    rng = np.random.default_rng(11)
    g_tips = np.full((n, 3), np.nan)
    g_pass = np.full((n, 3), np.nan)
    g_errs = np.full(n, np.nan)
    x_hist = [np.zeros(3)]
    t0 = time.time()
    n_rescue = 0
    for j, q2 in enumerate(q2s):
        x_warm = x_hist[-1]
        x_pred = 2.0 * x_hist[-1] - x_hist[-2] if len(x_hist) > 1 else x_warm
        x, foot = solve_tracked(q2, x_warm, x_pred, rng)
        if x is None:
            print(f"  FAILED at q2={q2:.4f}")
            continue
        if not np.allclose(x, x_warm, atol=1e-9):
            n_rescue += 1
        x_hist.append(x)
        g_tips[j] = foot * 1000.0
        g_pass[j] = x
        g_errs[j] = 0.0
        if (j + 1) % 120 == 0:
            print(f"  gen {j + 1}/{n}  ({time.time() - t0:.0f} s)")
    print(f"generator done in {time.time() - t0:.0f} s, steps off the bare continuation: {n_rescue}")
    step = np.linalg.norm(np.diff(g_tips, axis=0), axis=1)
    k = int(np.argmax(step))
    print(f"max generator step {step.max():.2f} mm at q2={q2s[k]:.3f}")
    print(f"max |q5 - q2| over branch: {np.nanmax(np.abs(g_pass[:, 2] - q2s)):.2e} rad")
    x_end, _, foot_end = solve_passive(0.0, q2s[-1] + 2 * np.pi / n, g_pass[-1])
    print(f"period closure: tip diff {np.linalg.norm(foot_end * 1000 - g_tips[0]):.4f} mm, "
          f"passive diff {np.max(np.abs(x_end - g_pass[0])):.2e} rad")
    return q2s, g_tips, g_pass, g_errs


def build_surface(g_tips, n_rot=280):
    """Apply the q1 revolution analytically: tips(q1, q2) = R(U_PLOT, q1) g(q2),
    with closed seams in both parameters."""
    q1s = np.linspace(0.0, 2.0 * np.pi, n_rot + 1)
    G = np.vstack([g_tips / 1000.0, g_tips[:1] / 1000.0])  # closed, metres
    tips = np.empty((len(q1s), len(G), 3))
    for i, q1 in enumerate(q1s):
        R = rot_axis(U_PLOT, q1)[:3, :3]
        tips[i] = (R @ G.T).T
    return q1s, tips * 1000.0


def halfcut_start(tips):
    """Start angle a0 of the pi-window of the revolution whose surface has the
    lowest mean z (the 'lower half' cut-away window)."""
    zbar = np.nanmean(tips[:-1, :, 2], axis=1)      # mean tip z at each q1 step
    n = len(zbar)
    w = n // 2                                       # window = half revolution
    c = np.concatenate([[0.0], np.cumsum(np.tile(zbar, 2))])
    means = (c[np.arange(n) + w] - c[np.arange(n)]) / w
    return 2.0 * np.pi * int(np.argmin(means)) / n


def validate_surface(q2s, g_pass, n_check=80):
    """Random (q1, q2) points: the passive solution must be g_pass(q2) itself
    (closure independent of q1) -- hard check of the revolution construction."""
    rng = np.random.default_rng(5)
    ok, max_dev, max_e = 0, 0.0, 0.0
    for _ in range(n_check):
        q1 = rng.uniform(-2 * np.pi, 2 * np.pi)
        j = int(rng.integers(0, len(q2s)))
        x, e, _ = solve_passive(q1, q2s[j], g_pass[j])
        max_e = max(max_e, e)
        max_dev = max(max_dev, float(np.max(np.abs(x - g_pass[j]))))
        ok += e < 1e-11 and np.linalg.norm(x - g_pass[j]) < 1e-7
    print(f"validation: {ok}/{n_check} exact (max passive dev {max_dev:.1e} rad, "
          f"max closure {max_e:.1e} m)")


# ------------------------------------------------------------------- drawing --
def style3d(ax):
    ax.set_facecolor(SURFACE)
    for pane in (ax.xaxis.pane, ax.yaxis.pane, ax.zaxis.pane):
        pane.set_facecolor(SURFACE)
        pane.set_edgecolor(GRID)
    ax.tick_params(colors=INK, labelsize=7.5, pad=-1)
    for axis in (ax.xaxis, ax.yaxis, ax.zaxis):
        axis._axinfo["grid"].update({"color": GRID, "linewidth": 0.6})
        axis.line.set_color(MUTED)


def add_triad(ax, scale, zorder=None):
    for d in np.eye(3):
        ax.quiver(0, 0, 0, *(d * scale), color="#7b2d8b", linewidth=1.6,
                  arrow_length_ratio=0.12, zorder=zorder)


def add_axis3d(ax, lim):
    """Drive-axis z1 reference line through the hip origin, dashed, drawn
    behind the surface so it reads as sticking out at both ends."""
    L = 1.04 * lim
    u = U_PLOT
    ax.plot([-L * u[0], L * u[0]], [-L * u[1], L * u[1]], [-L * u[2], L * u[2]],
            color=INK2, linewidth=0.9, linestyle=(0, (5, 4)), alpha=0.95, zorder=0)
    ax.text(1.10 * L * u[0], 1.10 * L * u[1], 1.10 * L * u[2], "$z_1$",
            color=INK2, fontsize=8, ha="center", va="bottom")


def add_axis_side(ax, lim):
    """The same drive axis projected into the y-z side view: the upper-left to
    lower-right diagonal through the origin."""
    L = 1.04 * lim
    ax.plot([-L * U_PLOT[1], L * U_PLOT[1]], [-L * U_PLOT[2], L * U_PLOT[2]],
            color=INK2, linewidth=0.9, linestyle=(0, (5, 4)), alpha=0.95, zorder=0.5)
    ax.text(1.10 * L * U_PLOT[1], 1.10 * L * U_PLOT[2], "$z_1$",
            color=INK2, fontsize=8, ha="right", va="bottom")


def nice_lim(tips):
    return 50.0 * np.ceil(np.nanmax(np.abs(tips)) * 1.05 / 50.0)


def ortho_scatter(ax, tips, cmap, norm, stride=2, alpha=1.0):
    z = tips[::stride, ::stride, 2]
    pts = tips[::stride, ::stride, :2]
    order = np.argsort(z.ravel())
    ax.scatter(pts[:, :, 0].ravel()[order], pts[:, :, 1].ravel()[order],
               c=z.ravel()[order], s=0.8, cmap=cmap, norm=norm, linewidths=0,
               alpha=alpha, rasterized=True)


def ortho_fill(ax, tips, cmap, norm, xy=(1, 2), stride_q2=2):
    """Filled orthographic projection of the parametric surface onto a coordinate
    plane: tripcolor over the (q1, q2) grid -- no point-cloud moire."""
    i, j = xy
    P = tips[:, ::stride_q2, :]
    n1, n2 = P.shape[0], P.shape[1]
    xv = P[:, :, i].ravel()
    yv = P[:, :, j].ravel()
    zv = P[:, :, 2].ravel()
    idx = np.arange(n1 * n2).reshape(n1, n2)
    t1 = np.stack([idx[:-1, :-1], idx[1:, :-1], idx[1:, 1:]], axis=-1).reshape(-1, 3)
    t2 = np.stack([idx[:-1, :-1], idx[1:, 1:], idx[:-1, 1:]], axis=-1).reshape(-1, 3)
    ax.tripcolor(xv, yv, np.vstack([t1, t2]), zv, cmap=cmap, norm=norm,
                 shading="gouraud", rasterized=True, snap=False)


def style_ortho(ax, lim):
    ax.set_aspect("equal")
    ax.set_facecolor(SURFACE)
    for side in ax.spines.values():
        side.set_color(MUTED)
        side.set_linewidth(0.8)
    ax.grid(color=GRID, linewidth=0.6)
    ax.set_axisbelow(True)
    ax.tick_params(colors=INK, labelsize=7.5)
    ax.set_xlim(-lim, lim)
    ax.set_ylim(-lim, lim)


def three_view_fig():
    fig = plt.figure(figsize=(12.2, 5.9), facecolor=SURFACE, constrained_layout=True)
    gs = fig.add_gridspec(2, 2, width_ratios=[1.42, 1.0])
    ax3d = fig.add_subplot(gs[:, 0], projection="3d")
    ax_side = fig.add_subplot(gs[0, 1])
    ax_front = fig.add_subplot(gs[1, 1])
    return fig, ax3d, ax_side, ax_front


def finish_ortho(ax, title, lim):
    ax.set_title(title, fontsize=9.5, color=INK, loc="left")
    ax.set_xlabel("y (mm)" if "Side" in title else "x (mm)", fontsize=8.5, color=INK)
    ax.set_ylabel("z (mm)", fontsize=8.5, color=INK)
    style_ortho(ax, lim)


def plot_fig5(q1s, tips, g_tips, out_dir, cut=True, fname="fig5_workspace"):
    cmap = plt.get_cmap("turbo")
    norm = plt.Normalize(np.nanmin(tips[:, :, 2]), np.nanmax(tips[:, :, 2]))
    lim = nice_lim(tips)

    fig, ax3d, ax_side, ax_front = three_view_fig()
    add_axis3d(ax3d, lim)
    if cut:
        # half-cut-away isometric: keep the pi-window of the revolution whose
        # surface sits lowest; the cut edges are the generator curve itself
        a0 = halfcut_start(tips)
        n_half = (len(q1s) - 1) // 2
        q1h = np.linspace(a0, a0 + np.pi, n_half + 1)
        G = np.vstack([g_tips / 1000.0, g_tips[:1] / 1000.0])
        half = np.empty((len(q1h), len(G), 3))
        for i, a in enumerate(q1h):
            R = rot_axis(U_PLOT, a)[:3, :3]
            half[i] = (R @ G.T).T
        half *= 1000.0
        surf = ax3d.plot_surface(half[:, :, 0], half[:, :, 1], half[:, :, 2],
                                 cmap=cmap, norm=norm, rstride=2, cstride=2,
                                 linewidth=0.1, edgecolor=(0, 0, 0, 0.14),
                                 shade=False, antialiased=True, rasterized=True)
        for a_edge in (a0, a0 + np.pi):
            R = rot_axis(U_PLOT, a_edge)[:3, :3]
            edge = (R @ G.T).T * 1000.0
            ax3d.plot(edge[:, 0], edge[:, 1], edge[:, 2], color=INK, linewidth=1.5,
                      zorder=5)
    else:
        surf = ax3d.plot_surface(tips[:, :, 0], tips[:, :, 1], tips[:, :, 2],
                                 cmap=cmap, norm=norm, rstride=2, cstride=2,
                                 linewidth=0.1, edgecolor=(0, 0, 0, 0.14),
                                 shade=False, antialiased=True, rasterized=True)
    add_triad(ax3d, 0.22 * lim)
    style3d(ax3d)
    ax3d.set_xlabel("x (mm)", fontsize=8.5, color=INK)
    ax3d.set_ylabel("y (mm)", fontsize=8.5, color=INK)
    ax3d.set_zlabel("z (mm)", fontsize=8.5, color=INK)
    ax3d.set_box_aspect((1, 1, 1))
    ax3d.view_init(elev=22, azim=-60)
    ax3d.set_xlim(-lim, lim)
    ax3d.set_ylim(-lim, lim)
    ax3d.set_zlim(-lim, lim)

    ortho_fill(ax_side, tips, cmap, norm, xy=(1, 2))
    add_axis_side(ax_side, lim)
    finish_ortho(ax_side, "Side view (y-z)", lim)
    ortho_fill(ax_front, tips, cmap, norm, xy=(0, 2))
    finish_ortho(ax_front, "Front view (x-z)", lim)

    cb = fig.colorbar(surf, ax=ax3d, shrink=0.6, pad=0.06)
    cb.set_label("tip z (mm)", fontsize=8, color=INK)
    cb.ax.tick_params(labelsize=7, colors=INK)
    cb.outline.set_edgecolor(MUTED)

    sub = "Theoretical workspace of the Bennett leg (Urdf_Bennett_3, full actuator cycle)"
    if cut:
        sub += "\nisometric: half-cut-away view, cut edges = generator curve $g(q_2)$"
    fig.suptitle(sub, fontsize=11.5, color=INK)
    for name in (f"{fname}.png", f"{fname}.svg"):
        fig.savefig(out_dir / name, dpi=300, facecolor=SURFACE)
        print(f"  wrote {name}")
    plt.close(fig)


def plot_fig5b(q1s, tips, q2s, g_tips, g_pass, out_dir):
    cmap = plt.get_cmap("turbo")
    norm = plt.Normalize(np.nanmin(tips[:, :, 2]), np.nanmax(tips[:, :, 2]))
    lim = nice_lim(tips)

    # hardware-limited patch: q1 in [-0.8, 0.8], calf over [-0.9, 0.55] (wraps at 2pi)
    n1b, n = 49, len(q2s)
    q1b = np.linspace(-THIGH_LIMIT, THIGH_LIMIT, n1b)
    dq = 2.0 * np.pi / n
    ja = int(round((CALF_LIMITS[1] - Q2_START) / dq))          # q2 = +0.55
    jb = int(round(((CALF_LIMITS[0] - Q2_START) % (2 * np.pi)) / dq))  # q2 = -0.9 (wrapped)
    Gc = np.vstack([g_tips / 1000.0, g_tips[:1] / 1000.0])     # closed generator, m
    j_idx = np.concatenate([np.arange(jb, n + 1), np.arange(1, ja + 1)])
    band = np.empty((n1b, len(j_idx), 3))
    for i, q1 in enumerate(q1b):
        R = rot_axis(U_PLOT, q1)[:3, :3]
        band[i] = (R @ Gc[j_idx].T).T
    band *= 1000.0
    # boundary curves
    b_lo, b_hi = band[0], band[-1]                              # q1 = -0.8 / +0.8 arcs
    e_lo, e_hi = band[:, 0], band[:, -1]                        # q2 = -0.9 / +0.55 arcs

    # rest pose (standing defaults: thigh 0.08, calf -0.16), displayed on the
    # mirrored FR leg
    _, _, rest = solve_passive(0.08, -0.16, np.zeros(3))
    rest = rest * 1000.0 * MIR

    fig, ax3d, ax_side, ax_front = three_view_fig()
    add_axis3d(ax3d, lim)
    # ghost backdrop: full theoretical torus, light so the usable patch reads
    ax3d.plot_surface(tips[:, :, 0], tips[:, :, 1], tips[:, :, 2],
                      color="#dad8cf", rstride=2, cstride=2,
                      linewidth=0.1, edgecolor=(0, 0, 0, 0.10),
                      shade=False, antialiased=True, rasterized=True, alpha=0.30)
    ax3d.plot_surface(band[:, :, 0], band[:, :, 1], band[:, :, 2],
                      cmap=cmap, norm=norm, rstride=1, cstride=1,
                      linewidth=0.1, edgecolor=(0, 0, 0, 0.18),
                      shade=False, antialiased=True, rasterized=True)
    for curve in (b_lo, b_hi, e_lo, e_hi):
        ax3d.plot(curve[:, 0], curve[:, 1], curve[:, 2], color=INK, linewidth=1.8,
                  zorder=5)
    ax3d.scatter(*rest, color=INK, marker="*", s=150, depthshade=False,
                 edgecolors=SURFACE, linewidths=0.7, zorder=6)
    add_triad(ax3d, 0.22 * lim)
    style3d(ax3d)
    ax3d.set_xlabel("x (mm)", fontsize=8.5, color=INK)
    ax3d.set_ylabel("y (mm)", fontsize=8.5, color=INK)
    ax3d.set_zlabel("z (mm)", fontsize=8.5, color=INK)
    ax3d.set_box_aspect((1, 1, 1))
    ax3d.view_init(elev=22, azim=-60)
    ax3d.set_xlim(-lim, lim)
    ax3d.set_ylim(-lim, lim)
    ax3d.set_zlim(-lim, lim)

    ortho_fill(ax_side, tips, cmap, norm, xy=(1, 2))
    add_axis_side(ax_side, lim)
    for curve in (b_lo, b_hi, e_lo, e_hi):
        ax_side.plot(curve[:, 1], curve[:, 2], color=INK, linewidth=1.3)
    ax_side.scatter(rest[1], rest[2], color=INK, marker="*", s=150,
                    edgecolors=SURFACE, linewidths=0.7, zorder=6)
    finish_ortho(ax_side, "Side view (y-z)", lim)
    ortho_fill(ax_front, tips, cmap, norm, xy=(0, 2))
    for curve in (b_lo, b_hi, e_lo, e_hi):
        ax_front.plot(curve[:, 0], curve[:, 2], color=INK, linewidth=1.3)
    ax_front.scatter(rest[0], rest[2], color=INK, marker="*", s=150,
                     edgecolors=SURFACE, linewidths=0.7, zorder=6)
    finish_ortho(ax_front, "Front view (x-z)", lim)

    cb = fig.colorbar(None, ax=ax3d, cmap=cmap, norm=norm, shrink=0.6, pad=0.06)
    cb.set_label("tip z (mm)", fontsize=8, color=INK)
    cb.ax.tick_params(labelsize=7, colors=INK)
    cb.outline.set_edgecolor(MUTED)

    fig.suptitle("Bennett leg workspace with hardware joint limits\n"
                 f"colored patch = thigh $\pm$0.8 rad $\\times$ calf $-$0.9…+0.55 rad "
                 "(ghost = full theoretical workspace), $\\bigstar$ = rest pose (FR)",
                 fontsize=11, color=INK)
    for name in ("fig5b_workspace_limited.png", "fig5b_workspace_limited.svg"):
        fig.savefig(out_dir / name, dpi=300, facecolor=SURFACE)
        print(f"  wrote {name}")
    plt.close(fig)


# ---------------------------------------------------------------------- main --
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--n_gen", type=int, default=721, help="generator points per q2 period")
    parser.add_argument("--n_rot", type=int, default=280, help="revolution steps over full q1 cycle")
    parser.add_argument("--rescan", action="store_true")
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    cache = OUT_DIR / "workspace_generator.npz"
    if cache.exists() and not args.rescan:
        d = np.load(cache)
        q2s, g_tips, g_pass, g_errs = d["q2s"], d["g_tips"], d["g_pass"], d["g_errs"]
        print(f"loaded cached generator {cache.name} (n={len(q2s)})")
    else:
        print(f"scanning generator, {args.n_gen} points over one q2 period ...")
        q2s, g_tips, g_pass, g_errs = scan_generator(args.n_gen)
        np.savez_compressed(cache, q2s=q2s, g_tips=g_tips, g_pass=g_pass, g_errs=g_errs)
        print(f"  cached -> {cache}")

    # display orientation: mirror y -> FR leg (exact mirror, see module docstring)
    g_tips = g_tips * MIR

    q1s, tips = build_surface(g_tips, args.n_rot)
    validate_surface(q2s, g_pass)
    d_ax = tips - np.einsum("ijk,k->ij", tips, U_PLOT)[..., None] * U_PLOT
    print(f"tip reach: |tip| in [{np.linalg.norm(tips, axis=2).min():.0f}, "
          f"{np.linalg.norm(tips, axis=2).max():.0f}] mm, axis radius in "
          f"[{np.linalg.norm(d_ax, axis=2).min():.0f}, {np.linalg.norm(d_ax, axis=2).max():.0f}] mm")

    plot_fig5(q1s, tips, g_tips, OUT_DIR, cut=True, fname="fig5_workspace")
    plot_fig5(q1s, tips, g_tips, OUT_DIR, cut=False, fname="fig5_workspace_full")
    plot_fig5b(q1s, tips, q2s, g_tips, g_pass, OUT_DIR)


if __name__ == "__main__":
    main()
